# Generated by Django 4.0.4 on 2022-05-06 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65, verbose_name='Título')),
                ('description', models.CharField(max_length=165, verbose_name='Descrição')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('preparation_time', models.IntegerField(verbose_name='Tempo de preparo')),
                ('preparation_time_unit', models.CharField(max_length=30, verbose_name='Unidade de Tempo')),
                ('servings', models.IntegerField(verbose_name='Porções')),
                ('servings_unit', models.CharField(max_length=50, verbose_name='Unidade de Porções')),
                ('preparation_steps', models.TextField(verbose_name='Passos para a Preparação')),
                ('preparation_steps_is_html', models.BooleanField(default=False, verbose_name='Os passos de Preparação são HTML')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Criado em')),
                ('id_published', models.BooleanField(default=False, verbose_name='Foi publicado')),
                ('cover', models.ImageField(upload_to='recipes/covers/%Y/%m/%d/', verbose_name='Imagem')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.category')),
            ],
        ),
    ]
