# Generated by Django 4.0.4 on 2022-05-06 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='id_published',
            new_name='is_published',
        ),
    ]
